# Generated by Django 4.1.3 on 2022-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='advocate/')),
                ('username', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('bio', models.TextField(max_length=3000)),
                ('twitter', models.URLField(max_length=2048)),
            ],
        ),
    ]
